<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div>
    <?php $lastMessages = $block->getLastMessages() ?>
    <form class="form"
          action="javascript:void(0);"
          id="bogdank-support-chat-form"
          method="post"
          data-mage-init='{"bogdank_supportChat_chatForm":{
            "action": "<?= $block->escapeUrl($block->getUrl('supportchat/supportmessage/send')) ?>"
          }}'
          onsubmit="return false;"
          style="display: none;"
    >
        <?php /** @var \Bogdank\SupportChat\Block\MessageList $block */ ?>
        <div>
            <ul id="chat-messages">
                <?php /** @var \Bogdank\SupportChat\Model\SupportMessage $supportMessage */
                foreach ($lastMessages as $supportMessage) : ?>
                    <li class="message-item <?= $block->escapeHtmlAttr($supportMessage->getUserType()) ?>">
                        <p class="customer-name"><?= $block->escapeHtml($supportMessage->getUserName()) ?> <?= $block->escapeHtml($supportMessage->getCreatedAt()) ?></p>
                        <p class="customer-message-body"><?= $block->escapeHtml($supportMessage->getMessage()) ?></p>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <fieldset class="fieldset">
            <legend class="legend">
                <span><?= $block->escapeHtml(__('Contact Us')) ?></span>
            </legend>
            <div class="field name required">
                <label class="label" for="name">
                    <span><?= $block->escapeHtml(__('Name')) /* @TODO: get attribute label translation */ ?></span>
                </label>
                <div class="control">
                    <input name="name"
                           title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                           class="input-text"
                           type="text"
                           data-validate="{required:true}"
                    />
                </div>
            </div>
            <div class="field email required">
                <label class="label" for="message">
                    <span><?= $block->escapeHtml(__('Message')) ?></span>
                </label>
                <div class="control">
                    <input type="hidden"
                           name="chat_hash"
                           id="chat_hash"
                           value="<?= $block->escapeHtmlAttr($block->getChatHashCookie()) ?>"
                    />
                    <input name="message"
                           title="<?= $block->escapeHtmlAttr(__('Message')) ?>"
                           class="input-text"
                           type="text"
                           data-validate="{required:true}"
                    />
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value=""/>
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Send')) ?>" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Send')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>