<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div id="bogdank-support-chat-form-container" data-bind="scope: 'supportChatChatForm',
mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'title': 'Popup title',
            'trigger': '[data-trigger=trigger]',
            'responsive': true
        }}
">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#bogdank-support-chat-form-container": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        }
    }
</script>
</div>