<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div id="bogdank-support-chat-form-container" data-bind="scope: 'supportChatChatForm'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#bogdank-support-chat-form-container": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        }
    }
</script>
</div>